//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperFinance {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SFMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SFMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuperFinance.SFMessages", typeof(SFMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account with the same account number {0} already exists..
        /// </summary>
        public static string CannotAddDuplicateAccount {
            get {
                return ResourceManager.GetString("CannotAddDuplicateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type with the same name {0} already exists..
        /// </summary>
        public static string CannotAddDuplicateAccountType {
            get {
                return ResourceManager.GetString("CannotAddDuplicateAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank with the same name {0} already exists..
        /// </summary>
        public static string CannotAddDuplicateBank {
            get {
                return ResourceManager.GetString("CannotAddDuplicateBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch with the same code {0} already exists..
        /// </summary>
        public static string CannotAddDuplicateBranch {
            get {
                return ResourceManager.GetString("CannotAddDuplicateBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominee couldn&apos;t be added.
        /// </summary>
        public static string CannotAddNominee {
            get {
                return ResourceManager.GetString("CannotAddNominee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch manager couldn&apos;t be assigned – either the staff is already assigned or your account doesn&apos;t have a right to assign the branch manager..
        /// </summary>
        public static string CannotAssignBranchManager {
            get {
                return ResourceManager.GetString("CannotAssignBranchManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified account type couldn&apos;t be deleted as it has resources associated that must be deleted first..
        /// </summary>
        public static string CannotDeleteAccountType {
            get {
                return ResourceManager.GetString("CannotDeleteAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified branch couldn&apos;t be deleted as it has resources associated that must be deleted first..
        /// </summary>
        public static string CannotDeleteBranch {
            get {
                return ResourceManager.GetString("CannotDeleteBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no such branch manager to remove..
        /// </summary>
        public static string CannotDeleteBranchManager {
            get {
                return ResourceManager.GetString("CannotDeleteBranchManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified IP range couldn&apos;t be deleted as it has resources associated that must be deleted first..
        /// </summary>
        public static string CannotDeleteIpRange {
            get {
                return ResourceManager.GetString("CannotDeleteIpRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominee couldn&apos;t be deleted.
        /// </summary>
        public static string CannotDeleteNominee {
            get {
                return ResourceManager.GetString("CannotDeleteNominee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bank policy does not allow you to disable the multi factor authentication.
        /// </summary>
        public static string CannotDisableMFA {
            get {
                return ResourceManager.GetString("CannotDisableMFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit created successfully.
        /// </summary>
        public static string DepositCreated {
            get {
                return ResourceManager.GetString("DepositCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firewall status is successfully changed..
        /// </summary>
        public static string FirewallStatusIsChanged {
            get {
                return ResourceManager.GetString("FirewallStatusIsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFA token {0} is invalid..
        /// </summary>
        public static string InvalidMFAToken {
            get {
                return ResourceManager.GetString("InvalidMFAToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password expiration days cannot be less than 30..
        /// </summary>
        public static string InvalidPasswordExpirationDays {
            get {
                return ResourceManager.GetString("InvalidPasswordExpirationDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bank requires you to enable Two-Factor Authentication, please enable it to proceed..
        /// </summary>
        public static string MFAEnforced {
            get {
                return ResourceManager.GetString("MFAEnforced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two factor authentication policy is successfully updated. .
        /// </summary>
        public static string MFAPolicyIsChanged {
            get {
                return ResourceManager.GetString("MFAPolicyIsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominee created successfully.
        /// </summary>
        public static string NomineeCreated {
            get {
                return ResourceManager.GetString("NomineeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominee invited on the platform.
        /// </summary>
        public static string NomineeInvited {
            get {
                return ResourceManager.GetString("NomineeInvited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified username {0} is not a customer user..
        /// </summary>
        public static string NotACustomerUser {
            get {
                return ResourceManager.GetString("NotACustomerUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password expiration policy is successfully updated..
        /// </summary>
        public static string PasswordExpirationPolicyIsChanged {
            get {
                return ResourceManager.GetString("PasswordExpirationPolicyIsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is expired. Please reset the password..
        /// </summary>
        public static string PasswordExpired {
            get {
                return ResourceManager.GetString("PasswordExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer created successfully.
        /// </summary>
        public static string TransferCreated {
            get {
                return ResourceManager.GetString("TransferCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your two factor authentication setting is updated..
        /// </summary>
        public static string TwoFactorAuthChanged {
            get {
                return ResourceManager.GetString("TwoFactorAuthChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawal created successfully.
        /// </summary>
        public static string WithdrawalCreated {
            get {
                return ResourceManager.GetString("WithdrawalCreated", resourceCulture);
            }
        }
    }
}
